[project]
name = "github-stars-visualizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.0",
    "plotly[express]>=6.1.2",
    "pytest>=8.4.1",
    "requests>=2.32.4",
]
